name: Build CHIP-8 emulator Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26"

      - name: Download dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y \
            libc6-dev \
            libgl1-mesa-dev \
            libxcursor-dev \
            libxi-dev \
            libxinerama-dev \
            libxrandr-dev \
            libxxf86vm-dev \
            libasound2-dev \
            pkg-config
      - name: Build and copy Chip-8 binary for linux x86_64
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/chip8_linux_x86 cmd/chip8/main.go
          
      - name: Build and copy Chip-8 binary for windows x86_64
        run: |
          mkdir -p dist
          GOOS=windows GOARCH=amd64 go build -o dist/chip8_windows_x86.exe cmd/chip8/main.go

      - name: Build copy and zip Chip-8 binary for wasm
        run: |
          mkdir -p dist
          GOOS=js GOARCH=wasm go build -o dist/game.wasm cmd/chip8/main.go
          cp "$(go env GOROOT)/lib/wasm/wasm_exec.js" dist/wasm_exec.js
          cp web/index.html dist/index.html
          zip -j dist/chip8_wasm.zip dist/game.wasm dist/wasm_exec.js
        

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*